//Crypro List Actions
export const FETCH_CRYPTOLIST_BEGIN = 'FETCH_CRYPTOLIST_BEGIN';
export const FETCH_CRYPTOLIST_SUCCESS = 'FETCH_CRYPTOLIST_SUCCESS';
export const FETCH_CRYPTOLIST_FAILURE = 'FETCH_CRYPTOLIST_FAILURE';

//Indiviual Crypto Detail Actions
export const FETCH_INDIVIDUAL_CRYPTO_BEGIN = 'FETCH_INDIVIDUAL_CRYPTO_BEGIN';
export const FETCH_INDIVIDUAL_CRYPTO_SUCCESS = 'FETCH_INDIVIDUAL_CRYPTO_SUCCESS';
export const FETCH_INDIVIDUAL_CRYPTO_FAILURE = 'FETCH_INDIVIDUAL_CRYPTO_FAILURE';

//Other Actions...
export const ADD_CRYPTOLIST = 'ADD_CRYPTOLIST';
export const ADD_CRYPTOLIST_INTO_NEWLIST = 'ADD_CRYPTOLIST_INTO_NEWLIST';
