//List Actions
export const FETCH_CRYPTOLIST_BEGIN = 'FETCH_CRYPTOLIST_BEGIN';
export const FETCH_CRYPTOLIST_SUCCESS = 'FETCH_CRYPTOLIST_SUCCESS';
export const FETCH_CRYPTOLIST_FAILURE = 'FETCH_CRYPTOLIST_FAILURE';

//Other Actions...